BEGIN;
INSERT INTO s335141.discipline_prerequisites (discipline_id, prerequisite_id) VALUES (6132, 6196) ON CONFLICT DO NOTHING;
INSERT INTO s335141.discipline_prerequisites (discipline_id, prerequisite_id) VALUES (6230, 6132) ON CONFLICT DO NOTHING;
INSERT INTO s335141.discipline_prerequisites (discipline_id, prerequisite_id) VALUES (6230, 6383) ON CONFLICT DO NOTHING;
INSERT INTO s335141.discipline_prerequisites (discipline_id, prerequisite_id) VALUES (6150, 6130) ON CONFLICT DO NOTHING;
INSERT INTO s335141.discipline_prerequisites (discipline_id, prerequisite_id) VALUES (6138, 6142) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 6408, 4, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 5989, 4, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 6336, 4, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 6404, 4, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 6393, 4, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 6166, 5, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 5946, 3, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 5910, 5, true) ON CONFLICT DO NOTHING;
INSERT INTO s335141.student_progress (student_id, discipline_id, grade, is_completed) VALUES (1, 6413, 3, true) ON CONFLICT DO NOTHING;
COMMIT;